# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            
tagline:          'Ricky Palaguachi'
description:      'Programmer and mathematician. Passionate about technology.'
url:              'www.rpalaguachi.com'
baseurl:          /

author:
  name:           'Ricky Palaguachi'

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/rpalaguachi/rpalaguachi.github.io

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jekyll-seo-tag